main/urls.py
from django.conf.urls import url
from . import views
app_name = 'main'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^about/$', views.about, name='about'),
	url(r'^map/$', views.map, name='map'),
	url(r'^test/$', views.test, name='test'),
	url(r'^poirst/$', views.poirst, name='poirst'),
	url(r'^result/$', views.result, name='result'),
	url(r'^dheatmap/$', views.dheatmap, name='dheatmap'),
	url(r'^cheatmap/$', views.cheatmap, name='cheatmap'),
	url(r'^category/$', views.category, name='category'),
	url(r'^userinfo/(?P<uid>\d+)/$', views.userinfo, name='userinfo'),
	url(r'^EmotionAnalysis/$', views.EmotionAnalysis, name='emotionanalysis'),
	url(r'^DaypartsAnalysis/$', views.DaypartsAnalysis, name='daypartsanalysis'),
	url(r'^POIAnalysis/$', views.POIAnalysis, name='poianalysis'),
	url(r'^RegionAnalysis/$', views.RegionAnalysis, name='regionanalysis'),
	url(r'^EmotionAnalysis/(?P<uid>\d+)/$', views.ea, name='ea'),
	url(r'^DaypartsAnalysis/(?P<uid>\d+)/$', views.da, name='da'),
	url(r'^POIAnalysis/(?P<uid>\d+)/$', views.pa, name='pa'),
	url(r'^RegionAnalysis/(?P<uid>\d+)/$', views.ra, name='ra'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace = 'main')),
    url(r'^user/', include('user.urls', namespace = 'user'))
]

user/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

app_name = 'user'
urlpatterns = [
	url(r'^login/$', login, 
	{'template_name': 'user/login.html'}, name='login'),
	url(r'^logout/$', views.logout_view, name='logout'),
	url(r'^register/$', views.register, name='register'),
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('main:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(
                username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('main:index'))
    context = {'form': form}
    return render(request, 'user/register.html', context)

user/templates/user/login.html
{%extends 'main/base_nsb.html'%}
{% load bootstrap3 %}
{% block header %}
<h2 class="text-center" style="color: lightblue">Log in to your account.</h2>
{% endblock header %}
{%block content%}
<form action="{%url 'user:login'%}" method="post" class="form">
    {%csrf_token%}
    {% bootstrap_form form %}
    {% buttons %}
    <button class="btn btn-primary btn-block" name='submit'>Log in</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{%url 'main:index'%}"/>
</form>
{%endblock content%}

user/templates/user/register.html
{%extends 'main/base_nsb.html'%}
{% load bootstrap3 %}
{% block header%}
<h2 class="text-center" style="color: lightblue">Create your own account, and enjoy the service we provided!</h2>
{% endblock header %}
{%block content%}
<form action="{%url 'user:register'%}" method="post" class="form">
    {%csrf_token%}
    {% bootstrap_form form %}
    {% buttons %}
    <button class="btn btn-primary btn-block" name='submit'>Register</button>
    {% endbuttons %}
    <input type="hidden" name="next" value="{%url 'main:index'%}"/>
</form>
{%endblock content%}