main/urls.py
from django.conf.urls import url
from . import views
app_name = 'main'
urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^about/$', views.about, name='about'),
	url(r'^map/$', views.map, name='map'),
	url(r'^test/$', views.test, name='test'),
	url(r'^poirst/$', views.poirst, name='poirst'),
	url(r'^result/$', views.result, name='result'),
	url(r'^dheatmap/$', views.dheatmap, name='dheatmap'),
	url(r'^cheatmap/$', views.cheatmap, name='cheatmap'),
	url(r'^category/$', views.category, name='category'),
	url(r'^userinfo/(?P<uid>\d+)/$', views.userinfo, name='userinfo'),
	url(r'^EmotionAnalysis/$', views.EmotionAnalysis, name='emotionanalysis'),
	url(r'^DaypartsAnalysis/$', views.DaypartsAnalysis, name='daypartsanalysis'),
	url(r'^POIAnalysis/$', views.POIAnalysis, name='poianalysis'),
	url(r'^RegionAnalysis/$', views.RegionAnalysis, name='regionanalysis'),
	url(r'^EmotionAnalysis/(?P<uid>\d+)/$', views.ea, name='ea'),
	url(r'^DaypartsAnalysis/(?P<uid>\d+)/$', views.da, name='da'),
	url(r'^POIAnalysis/(?P<uid>\d+)/$', views.pa, name='pa'),
	url(r'^RegionAnalysis/(?P<uid>\d+)/$', views.ra, name='ra'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('main.urls', namespace = 'main')),
    url(r'^user/', include('user.urls', namespace = 'user'))
]

main/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.core.paginator import Paginator
from django.core.paginator import PageNotAnInteger
from django.core.paginator import EmptyPage
from django.core import serializers
from django.contrib.auth.decorators import login_required
from . import models
from . import funcs
import json

# Create your views here.


def index(request):
    return render(request, 'main/index.html')


def about(request):
    return render(request, 'main/about.html')

@login_required
def map(request):
    return render(request, 'main/map.html')


@login_required
def result(request):
    if (request.method == 'POST' and 'input' in request.POST
            and request.POST['input']):
        search = True
        string = request.POST['input']
    elif(request.method == 'GET' and 'string' in request.GET):
        search = True
        string = request.GET.get('string')

    else:
        # return HttpResponseRedirect(reverse('main:index'))
        # data = "We could not perform this search. \
        # Search text is required when searching."
        search = False
    if(search):
        data = models.TravelPoiUserinfoSuzhou.objects.filter(
            screen_name__contains=string).order_by("created_at_int")
        page = request.GET.get('page')
        paginator = Paginator(data, 20)
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
        context = {'data': data, 'string': string}
        return render(request, 'main/result.html', context)
    else:
        return HttpResponseRedirect(reverse('main:index'))


@login_required
def userinfo(request, uid):
    userR = models.TravelPoiUserinfoSuzhou.objects.get(id=uid)
    #data = models.TravelPoiWeibosSuzhou.objects.filter(uid__exact=uid)
    data = models.TravelPoiUsersWeibodataSuzhou.objects.filter(
        userid__exact=uid).order_by('id')
    page = request.GET.get('page')
    paginator = Paginator(data, 20)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {'userR': userR, 'data': data}
    return render(request, 'main/userinfo.html', context)


@login_required
def test(request):
    page = request.GET.get('page')
    data = models.TravelPoiUserinfoSuzhou.objects.all().order_by('created_at_int')
    paginator = Paginator(data, 20)
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)
    context = {'data': data}
    return render(request, 'main/test.html', context)


@login_required
def EmotionAnalysis(request):
    # uid = 1216254405
    # data = models.TravelPoiUsersWeibodataSuzhou.objects.filter(userid__exact=uid).order_by('id')
    # lt = list(data.values_list('text',flat=True))
    # plotdiv = funcs.plots(lt)
    plotdiv = '''<div id="eb1342ac-4d8a-42b7-b0fc-c32919429d2c" style="height: 100%; width: 100%;"\
     class="plotly-graph-div"></div><script type="text/javascript">window.PLOTLYENV=window.PLOTLYENV || {};window.PLOTLYENV.BASE_URL="https://plot.ly";Plotly.newPlot("eb1342ac-4d8a-42b7-b0fc-c32919429d2c", \
     [{"type": "scatter", "x": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18], \
     "y": [0.5, 0.5, 0.73863857984543, 0.1946309953928, 0.5, 0.50593131780624, 0.84168702363968, 0.5, 0, 0.5, 0.5, 0.5, 0.99047619104385, 0.57216626405716, 0.5, 0.63471966981888, 0.32888880372047, 0.57931786775589]}], \
     {"xaxis": {"autorange": true}, "yaxis": {"autorange": true}}, {"showLink": true, "linkText": "Export to plot.ly"})</script>'''
    context = {'plot': plotdiv}
    return render(request, 'main/EmotionAnalysis.html', context)


@login_required
def DaypartsAnalysis(request):
    plotdiv = funcs.plot2()
    context = {'plot': plotdiv}
    return render(request, 'main/DaypartsAnalysis.html', context)


@login_required
def POIAnalysis(request):
    return render(request, 'main/POIAnalysis.html')


@login_required
def RegionAnalysis(request):
    plotdiv = funcs.plot1()
    context = {'plot': plotdiv}
    return render(request, 'main/ra.html', context)


@login_required
def ea(request, uid):
    data = models.TravelPoiUsersWeibodataSuzhou.objects.filter(
        userid__exact=uid).order_by('id')
    # if(data.count()>30):
    #     data = data[:30]
    lt = list(data.values_list('text', flat=True))
    plotdiv = funcs.plots(lt)
    context = {'plot': plotdiv}
    return render(request, 'main/EmotionAnalysis.html', context)


@login_required
def da(request, uid):
    data = models.TravelPoiUsersWeibodataSuzhou.objects.filter(
        userid__exact=uid).order_by('id')
    lt = list(data.values_list('created_at', flat=True))
    plotdiv = funcs.plots2(lt)
    context = {'plot': plotdiv}
    return render(request, 'main/da.html', context)


@login_required
def pa(request, uid):
    data = models.TravelPoiUsersWeibodataSuzhou.objects.filter(
        userid__exact=uid).order_by('id')
    lt = list(data.values_list('text', flat=True))
    poi = funcs.pois(lt)
    context = {'plot': poi}
    return render(request, 'main/POIAnalysis.html', context)


@login_required
def ra(request, uid):
    #plotdiv = funcs.plot1()
    userR = models.TravelPoiUserinfoSuzhou.objects.get(id=uid)
    #data = models.TravelPoiWeibosSuzhou.objects.filter(uid__exact=uid)
    data = models.TravelPoiUsersWeibodataSuzhou.objects.filter(
        userid__exact=uid).order_by('created_at')
    lat = list(data.values_list('latitude', flat=True))
    lon = list(data.values_list('longitude', flat=True))
    context = {'userR': userR, 'lat': json.dumps(lat), 'lon': json.dumps(lon)}
    return render(request, 'main/RegionAnalysis.html', context)


@login_required
def poirst(request):
    if (request.method == 'POST' and 'input' in request.POST
            and request.POST['input']):
        search = True
        string = request.POST['input']
    elif(request.method == 'GET' and 'string' in request.GET):
        search = True
        string = request.GET.get('string')

    else:
        # return HttpResponseRedirect(reverse('main:index'))
        # data = "We could not perform this search. \
        # Search text is required when searching."
        search = False
    if(search):
        data = models.DistinctPoisSuzhou.objects.filter(
            title__contains=string).exclude(checkin_num__exact=0).order_by("-checkin_user_num","-checkin_num")
        page = request.GET.get('page')
        paginator = Paginator(data, 20)
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
        context = {'data': data, 'string': string}
        return render(request, 'main/poirst.html', context)
    else:
        return HttpResponseRedirect(reverse('main:map'))

@login_required
def category(request):
    if (request.method == 'POST' and 'input' in request.POST
            and request.POST['input']):
        search = True
        string = request.POST['input']
    elif(request.method == 'GET' and 'string' in request.GET):
        search = True
        string = request.GET.get('string')

    else:
        # return HttpResponseRedirect(reverse('main:index'))
        # data = "We could not perform this search. \
        # Search text is required when searching."
        search = False
    if(search):
        data = models.DistinctPoisSuzhou.objects.filter(
            category_name__contains=string).exclude(checkin_num__exact=0).order_by("-checkin_user_num","-checkin_num")
        page = request.GET.get('page')
        paginator = Paginator(data, 20)
        try:
            data = paginator.page(page)
        except PageNotAnInteger:
            data = paginator.page(1)
        except EmptyPage:
            data = paginator.page(paginator.num_pages)
        context = {'data': data, 'string': string}
        return render(request, 'main/category.html', context)
    else:
        return HttpResponseRedirect(reverse('main:map'))

@login_required
def dheatmap(request):
    #plotdiv = funcs.plot1()
    #data = models.TravelPoiWeibosSuzhou.objects.filter(uid__exact=uid)
    #
    #
    data = models.TravelPoiUsersWeibodataSuzhou.objects.all()[:100000]
    lat = list(data.values_list('latitude', flat=True))
    lon = list(data.values_list('longitude', flat=True))
    date = list(data.values_list('created_at', flat=True))
    context = {'lat': json.dumps(lat), 'lon': json.dumps(lon), 'date': json.dumps(date)}
    return render(request, 'main/dheatmap.html', context)


@login_required
def cheatmap(request):
    if(request.method == 'GET' and 'string' in request.GET):
        search = True
        string = request.GET.get('string')

    else:
        # return HttpResponseRedirect(reverse('main:index'))
        # data = "We could not perform this search. \
        # Search text is required when searching."
        search = False
    if(search):
        data = models.DistinctPoisSuzhou.objects.filter(
            category_name__contains=string).exclude(checkin_num__exact=0).order_by("-checkin_user_num","-checkin_num")
        lat = list(data.values_list('latitude', flat=True))
        lon = list(data.values_list('longitude', flat=True))
        num = list(data.values_list('checkin_num', flat=True))
        context = {'string': string, 'lat': json.dumps(lat), 'lon': json.dumps(lon), 'num': json.dumps(num)}
        return render(request, 'main/cheatmap.html', context)
    else:
        return HttpResponseRedirect(reverse('main:map'))

main/templates/main/DaypartsAnalysis.html
{% extends "main/base.html" %}
{% block header %}
	<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<h3 style="color: lightblue">Dayparts Analysis</h3>
			<div align="right" style="color: #0095ff">
			<a href="{% url 'main:dheatmap' %}">时段热力图</a>
		</div>
{% endblock header %}
{% block content %}
	<div class="container">
		<div class="row">
			{# <div id="plot_container" class="col-md-8 col-md-offset-2">{{plot|safe}}</div>#}
			<div class="col-md-12 ">{{plot|safe}}</div>
		</div>
	</div>
{% endblock content %}

main/templates/main/EmotionAnalysis.html
{% extends "main/base.html" %}
{% block header %}
	<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<h3 style="color: lightblue">Emotion Analysis</h3>
{% endblock header %}
{% block content %}
	<div class="container">
		<div class="row">
			{# <div id="plot_container" class="col-md-8 col-md-offset-2">{{plot|safe}}</div>#}
			<div class="col-md-12 ">{{plot|safe}}</div>
		</div>
	</div>
{% endblock content %}

main/templates/main/RegionAnalysis.html
{% extends "main/base.html" %}
{% block header %}
	<h2 >UserInfo</h2>
	<h3 style="color: lightblue">
	<p><i>NickName</i> <a target="_blank"  href="https://weibo.com/u/{{userR.id}}">{{userR.screen_name}}</a>  <i>From</i> {{userR.location}} </p>
	<small><p style="color: lightblue"><i>Description</i>: {{userR.description}}</p></small>
	</h3>
	<h3 style="color: lightblue">Region Analysis</h3>
{% endblock header %}
{% block content %}
	<div id="container" style="width:1080px; height:780px"></div>
	</Br>
	<script src="http://webapi.amap.com/maps?v=1.4.2&key=caf311f4a319c559e83c98604e58f6e5"></script>
	<script type="text/javascript" src="http://cache.amap.com/lbs/static/addToolbar.js"></script>
	<script type="text/javascript">
		var moveData = new Array();
		var latR = {{ lat| safe}};
		var lonR = {{ lon| safe}};
		for (var i = latR.length - 1; i >= 0; i--) {
	// 鼠标右键，审核元素，选择 console 可以看到输入的值。
	moveData.push([lonR[i], latR[i]]);
	};


	const dataLength = moveData.length;
	const centerLng = moveData
	.map(function (i) {
	return i[0];
	})
	.reduce(function (a, b) {
	return a + b;
	}) / dataLength;
	const centerLat = moveData
	.map(function (i) {
	return i[1];
	})
	.reduce(function (a, b) {
	return a + b;
	}) / dataLength;

	var map = new AMap.Map('container', {
	resizeEnable: true,
	center: [centerLng, centerLat],
	zoom: 6  //zoom怎么根据坐标改变还是比较复杂的
	});
		
	var polyline = new AMap.Polyline({
	path: moveData,          //设置线覆盖物路径
	strokeColor: "#3366FF", //线颜色
	strokeOpacity: 1,       //线透明度
	strokeWeight: 5,        //线宽
	strokeStyle: "solid",   //线样式
	strokeDasharray: [10, 5] //补充线样式
	});
	polyline.setMap(map);
		
		var marker = new AMap.Marker({
		position: moveData[0],
		//position: moveData[moveData.length-1],
		title:"起点"
	});
		marker.setMap(map);
		
		var markert = new AMap.Marker({
		position: moveData[moveData.length-1],
		title: "终点"
	});
		markert.setMap(map);
	</script>
{% endblock content %}

main/templates/main/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="zh-CN">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE-edge">
		<meta name="viewpoint" content="width=device-width, initial-scale=1">
		{% bootstrap_css %}
		{% bootstrap_javascript %}
		<style type="text/css">
		html,body{height:100%}
		.footer{margin-top:-30px;height:30px;}
		.wrap{min-height:100%}
		.main{padding-bottom:30px;overflow:hidden;}
		</style>
	</head>
	<body background="http://www.pzpu.com/wp-content/uploads/2016/07/20160715040809-60.jpg">
		<div class="wrap">
			<div class="main">
				<!-- http://www.pzpu.com/wp-content/uploads/2016/07/20160715040809-60.jpg -->
				<!-- Static Navbar -->
				{% block nav %}
					{% include "main/nav.html" %}
				{% endblock nav %}
				<div class="container">
					<form action="{% url 'main:result' %}" method="post" class="form-inline">
						{% csrf_token %}
						<div class="input-group col-md-12">
							<input type="text" name="input" class="form-control input-md" placeholder="Search" />
							<span class="input-group-btn">
								<button class="btn btn-info btn-md" type="submit" onclick="onSubmit()">
								<i class="glyphicon glyphicon-search"></i>
								</button>
							</span>
						</div>
					</form>
				</div>
				<div class="container">
					<div class="">
						{% block header %}
						{% endblock header %}
					</div>
					<div>
						<!-- Body&Content -->
						{% block content %}
						{% endblock content %}
					</div>
				</div>
				
			</div>
			
		</div>
		<div class="footer">
			<div class="container">
				<small>
				<p style="color: lightblue" class="text-center">© 2017 DBA.
					由 <a href="https://www.djangoproject.com/" target="_blank" class="external" rel="nofollow">Django</a> 强力驱动.
				</p>
				<p style="color: lightblue" class="text-center">
					Made By <a href="{% url 'main:about' %}" target="_blank" class="external" rel="nofollow">DBA Group</a>.
				</p>
				</small>
			</div>
		</div>
	</body>
</html>

main/templates/main/category.html
{% extends "main/base_nsb.html" %}
{% block header %}
	<div class="container">
		<h3 style="color: lightblue">Category: {{ string }}</h3>
		<h3 style="color: lightblue">There are {{ data.paginator.count }} Results</h3>
		<div align="right" style="color: #0095ff">
			<a href="{% url 'main:cheatmap'%}?string={{ string }}">分类热力图</a>
		</div>
	</div>
{% endblock header %}
{% block content %}
	<div class="container">
		{% for item in data %}
			<div class="panel panel-default">
				<div class="panel-heading">
					{{ item.address}}
				</div>
				<div class="panel-body">
					Title:  {{ item.title }}
					CheckIn User Num: {{item.checkin_user_num}}
					CheckIn Num: {{item.checkin_num}}
				</div>
			</div>
			{% empty %}
			There are no entries in the database.
		{% endfor %}
	</div>
	<!-- 另一种分页显示方式 -->
	<p class="text-center">
		{% if data.has_previous %}
			<a href="?page={{ data.previous_page_number }}&string={{string}}">Previous</a>
		{% endif %}
		{# data.paginator.number_pages 返回总页数 #}
		<i style="color: lightblue">Page {{ data.number }} of {{ data.paginator.num_pages }}.</i>
		{% if data.has_next %}
			<a href="?page={{ data.next_page_number }}&string={{string}}">Next</a>
		{% endif %}
	</p>
{% endblock content %}

main/templates/main/cheatmap.html
{% extends "main/mapbase.html" %}
{% block header %}
	<div class="container">
		<h3 style="color: lightblue">Category: {{ string }}</h3>
	</div>
{% endblock header %}
{% block content %}
	<div id="container" tabindex="0" style="width:1080px; height:780px"></div>
	<script src="http://webapi.amap.com/maps?v=1.4.2&key=caf311f4a319c559e83c98604e58f6e5"></script>
<script type="text/javascript" src="http://cache.amap.com/lbs/static/addToolbar.js"></script>
	<script>

	// 这部分数据需要从接口获得，格式参见 heatmap.js 里的
	//heatmapData.forEach(function (i) {
	//i["count"] = 1;
	//});
	// 这里只取了200个点展示，不知道咱们的数据规模
	//heatmapData = heatmapData.slice(0, 200);
	
	let heatmapData = [];
	var latR = {{ lat| safe }};
	var lonR = {{ lon| safe }};
	var numR = {{ num| safe }};
	for (var i = latR.length - 1; i >= 0; i--) {
	heatmapData.push({"lng": lonR[i],
    "lat": latR[i],
    "count": numR[i]});
	};
	const dataLength = heatmapData.length;
	const centerLng = heatmapData
	.map(function (i) {
	return i.lng;
	})
	.reduce(function (a, b) {
	return a + b;
	}) / dataLength;
	const centerLat = heatmapData
	.map(function (i) {
	return i.lat;
	})
	.reduce(function (a, b) {
	return a + b;
	}) / dataLength;

	const map = new AMap.Map('container', {
	resizeEnable: true,
	zoom: 10, // 这个根据咱们的数据调吧
	center: [centerLng, centerLat],
	});
	let heatmap;
	map.plugin(["AMap.Heatmap"], function () {
	heatmap = new AMap.Heatmap(map, {
	// 这两个参数都是用的默认的，感觉应该不用动了
	radius: 25,
	opacity: [0, 0.8],
	});
	heatmap.setDataSet({
	data: heatmapData,
	max: 10, // 这个需要根据数据调
	});
	});
	</script>
{% endblock content %}

main/templates/main/da.html
{% extends "main/base.html" %}
{% block header %}
	<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<h3 style="color: lightblue">Dayparts Analysis</h3>
			<div align="right" style="color: #0095ff">
		</div>
{% endblock header %}
{% block content %}
	<div class="container">
		<div class="row">
			{# <div id="plot_container" class="col-md-8 col-md-offset-2">{{plot|safe}}</div>#}
			<div class="col-md-12 ">{{plot|safe}}</div>
		</div>
	</div>
{% endblock content %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% block header %}
	<!-- 	<div class="jumbotron" >
			<h2 class="text-center" >微博数据分析</h2>
	</div> -->
{% endblock header %}
{% block content %}
	<header class="col-xs-12 text-center infoheader">
		<h2 style="color:lightblue" class="text-lg-center">Weibo Data Analysis</h2>
		<p style="color:lightblue">
			Processing the data crawled from weibo.com, Powered by
			<a href="http://www.numpy.org/" target="_blank" class="external" rel="nofollow">numpy</a> ,
			<a href="https://plot.ly/" target="_blank" class="external" rel="nofollow">plotly</a>
			and <a href="https://matplotlib.org/basemap/" target="_blank" class="external" rel="nofollow">matplotlib_basemap</a> .
		</p>
	</header>
	<div class="container">
		<section class="col-xs-12 newsletters">
			<div class="row">
				<div class="col-6 col-md-6">
					<a href="{% url 'main:emotionanalysis'%}">
						<img class="img-thumbnail" height="400" width="400" src="http://i01.pic.sogou.com/2942371688d6c300" alt="">
					</a>
					<h4 style="color: lightblue">情绪分析</h4>
					<p style="color: lightblue">Text2Emotion Analysis based on database table TravelPoiWeibosSuzhou.</p>
				</div>
				<div class="col-6 col-md-6">
					<a href="{% url 'main:daypartsanalysis'%}">
						<img height="400" width="400" class="img-thumbnail" src="https://danianatasha.files.wordpress.com/2016/06/panda.jpg?w=255&h=255" alt="">
					</a>
					<h4 style="color: lightblue">时段统计</h4>
					<p style="color: lightblue">Dayparts Analysis based on database table TravelPoiWeibosSuzhou.</p>
				</div>
				<div class="col-6 col-md-6">
					<a href="{% url 'main:poianalysis'%}">
						<img height="400" width="400" class="img-thumbnail" src="http://img.mp.itc.cn/upload/20170413/e7aecb6155fd4dd098c1cb11e8308dc7.jpeg" alt="">
					</a>
					<h4 style="color: lightblue">兴趣点提取</h4>
					<p style="color: lightblue">POI Analysis based on database table TravelPoiWeibosSuzhou.</p>
				</div>
				<div class="col-6 col-md-6">
					<a href="{% url 'main:regionanalysis'%}">
						<img height="400" width="400" class="img-thumbnail" src="http://i01.pictn.sogoucdn.com/663da707c80217b5" alt="">
					</a>
					<h4 style="color: lightblue">地理位置</h4>
					<p style="color: lightblue">Region Analysis based on database table TravelPoiUserinfoSuzhou</p>
				</div>
			</div>
		</section>
	</div>
{% endblock content %}
<!-- 旅游地域统计 -->

main/templates/main/ra.html
{% extends "main/base.html" %}
{% block header %}
	<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
	<h3 style="color: lightblue">Region Analysis</h3>
{% endblock header %}
{% block content %}
<!-- 1607326654 -->
	<div class="container">
		<div class="row">
			{# <div id="plot_container" class="col-md-8 col-md-offset-2">{{plot|safe}}</div>#}
			<div class="col-md-12 ">{{plot|safe}}</div>
		</div>
	</div>
{% endblock content %}

main/templates/main/result.html
{% extends "main/base_nsb.html" %}
{% block header %}
	<div class="container">
		<h3 style="color: lightblue">There are {{ data.paginator.count }} Results</h3>
	</div>
{% endblock header %}
{% block content %}
	<div class="container">
		{% for item in data %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<a href="{% url 'main:userinfo' item.id %}">{{ item.screen_name}}</a>
					{{ item.location}}
				</div>
				<div class="panel-body">
					Description:  {{ item.description }}
				</div>
			</div>
			{% empty %}
			There are no entries in the database.
		{% endfor %}
	</div>
	<!-- 另一种分页显示方式 -->
	<p class="text-center">
		{% if data.has_previous %}
			<a href="?page={{ data.previous_page_number }}&string={{string}}">Previous</a>
		{% endif %}
		{# data.paginator.number_pages 返回总页数 #}
		<i style="color: lightblue">Page {{ data.number }} of {{ data.paginator.num_pages }}.</i>
		{% if data.has_next %}
			<a href="?page={{ data.next_page_number }}&string={{string}}">Next</a>
		{% endif %}
	</p>
{% endblock content %}

main/templates/main/test2.html
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div id="container" style="width:1080px; height:780px"></div>
</body>
<script type="text/javascript" src="http://webapi.amap.com/maps?v=1.4.2&key=caf311f4a319c559e83c98604e58f6e5"></script> 
<script type="text/javascript">
var map = new AMap.Map('container', {
    resizeEnable: true,
    zoom: 11,
    center: [120.610842,31.329724]        
});
</script>

</html>

main/templates/main/text.html
{% extends "main/base_nsb.html" %}
{% block header %}
	
{% endblock header %}
{% block content %}
# <img src="../../../static/{{ filename }}.png">
{% endblock content %}

main/templates/main/userinfo.html
{% extends "main/base_nsb.html" %}
{% block header %}
	<div style="color: lightblue">
		<!-- 1644412911 -->
		<!-- 1641815414-->
		<h2 >UserInfo</h2>
		<h3 style="color: lightblue">
		<p><i>NickName</i> <a target="_blank"  href="https://weibo.com/u/{{userR.id}}">{{userR.screen_name}}</a>  <i>From</i> {{userR.location}} </p>
		<small><p style="color: lightblue"><i>Description</i>: {{userR.description}}</p></small>
		</h3>
		<div align="right" style="color: #0095ff">
			<a href="{% url 'main:ea' userR.id %}">情绪分析</a>
			<a href="{% url 'main:da' userR.id %}">时段统计</a>
			<a href="{% url 'main:pa' userR.id %}">兴趣点提取</a>
			<a href="{% url 'main:ra' userR.id %}">地理位置</a>
		</div>
	</div>
{% endblock header %}
{% block content %}
	<div class="container">
		{% for item in data %}
			<div class="panel panel-default">
				<div class="panel-heading">
					<i style="color: lightblue">TimeStamp: {{ item.created_at}}</i>
				</div>
				<div class="panel-body">
					<strong>
					<p>Location (latitude: {{item.latitude}}  longitude: {{item.longitude}}) </p>
					</strong>
					{{ item.text }}
				</div>
			</div>
			{% empty %}
			There are no entries in the database.
		{% endfor %}
	</div>
	<!-- 另一种分页显示方式 -->
	<p class="text-center">
		{% if data.has_previous %}
			<a href="?page={{ data.previous_page_number }}&string={{string}}">Previous</a>
		{% endif %}
		{# data.paginator.number_pages 返回总页数 #}
		<i style="color: lightblue">Page {{ data.number }} of {{ data.paginator.num_pages }}.</i>
		{% if data.has_next %}
			<a href="?page={{ data.next_page_number }}&string={{string}}">Next</a>
		{% endif %}
	</p>
{% endblock content %}